-- 0020_multi_tenant_foundation — tenancy foundation (Phase 1 of the multi-tenant
-- transformation; see docs/plans/multi-tenant-phase0-audit-and-plan.md).
--
-- Generated by drizzle-kit from the entities, then HAND-HARDENED: the generated
-- `ADD COLUMN tenant_id ... DEFAULT current_setting('app.tenant_id', true)::uuid
-- NOT NULL` would evaluate the (unset) GUC for existing rows and fail NOT NULL.
-- Safe sequence instead:
--   1. create platform tables            5. guard assertions
--   2. seed the Masa tenant + dev plan   6. SET DEFAULT (GUC) + SET NOT NULL
--   3. add tenant_id columns (nullable)  7. FKs + re-scoped indexes
--   4. backfill every row to Masa        8. ENABLE RLS + tenant_isolation policies
--
-- The whole file runs in one transaction (drizzle migrator): all-or-nothing.
-- Backfill uses a CONSTANT tenant id: pre-0020 the entire database belongs to
-- the one Masa brand, so deriving via parent FKs would add risk, not safety.
-- Masa tenant id must match MASA_TENANT_ID in src/modules/tenants/tenants.constants.ts.
CREATE TABLE "api_keys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"name" text NOT NULL,
	"key_hash" text NOT NULL,
	"prefix" text NOT NULL,
	"scopes" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"last_used_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "channels" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"type" text DEFAULT 'messenger' NOT NULL,
	"page_id" text NOT NULL,
	"page_access_token_encrypted" text NOT NULL,
	"status" text DEFAULT 'connected' NOT NULL,
	"connected_at" timestamp with time zone DEFAULT now() NOT NULL,
	"meta" jsonb DEFAULT '{}'::jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "plans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"monthly_message_limit" integer,
	"monthly_token_limit" bigint,
	"price_micro_usd" integer DEFAULT 0 NOT NULL,
	"features" jsonb DEFAULT '{}'::jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "platform_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"role" text DEFAULT 'super_admin' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tenants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"plan_id" uuid,
	"settings" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "usage_daily" (
	"tenant_id" uuid NOT NULL,
	"day" date NOT NULL,
	"operation" text NOT NULL,
	"model" text NOT NULL,
	"sum_input" bigint DEFAULT 0 NOT NULL,
	"sum_output" bigint DEFAULT 0 NOT NULL,
	"sum_cached" bigint DEFAULT 0 NOT NULL,
	"sum_cost_micro" bigint DEFAULT 0 NOT NULL,
	"message_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "usage_daily_tenant_id_day_operation_model_pk" PRIMARY KEY("tenant_id","day","operation","model")
);
--> statement-breakpoint
CREATE TABLE "usage_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"conversation_id" uuid,
	"operation" text NOT NULL,
	"model" text NOT NULL,
	"input_tokens" integer DEFAULT 0 NOT NULL,
	"output_tokens" integer DEFAULT 0 NOT NULL,
	"cached_input_tokens" integer DEFAULT 0 NOT NULL,
	"cost_micro_usd" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "api_keys" ADD CONSTRAINT "api_keys_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "channels" ADD CONSTRAINT "channels_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tenants" ADD CONSTRAINT "tenants_plan_id_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."plans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usage_daily" ADD CONSTRAINT "usage_daily_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usage_events" ADD CONSTRAINT "usage_events_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "api_keys_key_hash_idx" ON "api_keys" USING btree ("key_hash");--> statement-breakpoint
CREATE INDEX "api_keys_tenant_id_idx" ON "api_keys" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX "channels_page_id_idx" ON "channels" USING btree ("page_id");--> statement-breakpoint
CREATE INDEX "channels_tenant_id_idx" ON "channels" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX "plans_name_idx" ON "plans" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "platform_users_email_idx" ON "platform_users" USING btree ("email");--> statement-breakpoint
CREATE UNIQUE INDEX "tenants_slug_idx" ON "tenants" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "usage_events_tenant_created_idx" ON "usage_events" USING btree ("tenant_id","created_at");--> statement-breakpoint
-- Seed the dev plan and the Masa tenant every pre-multi-tenant row backfills to.
-- Ids are pinned constants (tenants.constants.ts); ON CONFLICT keeps re-runs inert.
INSERT INTO "plans" ("id", "name", "monthly_message_limit", "monthly_token_limit", "price_micro_usd", "features")
VALUES ('aa5a0000-0000-4000-8000-000000000002', 'dev-unlimited', NULL, NULL, 0, '{}'::jsonb)
ON CONFLICT DO NOTHING;--> statement-breakpoint
INSERT INTO "tenants" ("id", "name", "slug", "status", "plan_id", "settings")
VALUES ('aa5a0000-0000-4000-8000-000000000001', 'Masa Fashion', 'masa', 'active', 'aa5a0000-0000-4000-8000-000000000002', '{}'::jsonb)
ON CONFLICT DO NOTHING;--> statement-breakpoint
-- Old single-tenant indexes superseded by tenant-composite ones below.
DROP INDEX "conversations_psid_idx";--> statement-breakpoint
DROP INDEX "knowledge_entries_is_published_idx";--> statement-breakpoint
DROP INDEX "ad_product_links_ad_ref_active_idx";--> statement-breakpoint
DROP INDEX "color_synonyms_term_idx";--> statement-breakpoint
DROP INDEX "colors_family_idx";--> statement-breakpoint
DROP INDEX "product_categories_slug_idx";--> statement-breakpoint
DROP INDEX "products_is_published_idx";--> statement-breakpoint
DROP INDEX "products_sku_idx";--> statement-breakpoint
-- tenant_id lands NULLABLE with NO default first; the GUC default would
-- evaluate to NULL for existing rows during the ALTER and break NOT NULL.
ALTER TABLE "admin_users" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "agent_behavior" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "conversation_events" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "conversations" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "conversations" ADD COLUMN "channel_id" uuid;--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "knowledge_entries" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "order_items" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "orders" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "ad_product_links" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "color_synonyms" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "colors" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "product_categories" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "product_image_colors" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "product_image_descriptions" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "product_image_embeddings" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
-- Backfill: every pre-multi-tenant row belongs to Masa (constant by definition —
-- the DB held exactly one brand before this migration).
UPDATE "admin_users" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "agent_behavior" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "conversation_events" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "conversations" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "messages" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "knowledge_entries" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "order_items" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "orders" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "ad_product_links" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "color_synonyms" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "colors" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "product_categories" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "product_image_colors" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "product_image_descriptions" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "product_image_embeddings" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
UPDATE "products" SET "tenant_id" = 'aa5a0000-0000-4000-8000-000000000001' WHERE "tenant_id" IS NULL;--> statement-breakpoint
-- Guards: the two new partial UNIQUE indexes must not be creatable over dirty
-- data silently. Fail the whole migration loudly instead.
DO $$
BEGIN
  IF (SELECT count(*) FROM "agent_behavior" WHERE "is_active") > 1 THEN
    RAISE EXCEPTION 'migration 0020: % active agent_behavior rows found — exactly one may be active; deactivate extras and re-run',
      (SELECT count(*) FROM "agent_behavior" WHERE "is_active");
  END IF;
  IF EXISTS (
    SELECT 1 FROM "orders"
    WHERE "status" = 'draft' AND "conversation_id" IS NOT NULL
    GROUP BY "conversation_id" HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'migration 0020: multiple draft orders share one conversation — resolve duplicates and re-run';
  END IF;
END $$;--> statement-breakpoint
-- Now the GUC default (new INSERTs inherit the transaction-bound tenant;
-- unset GUC -> NULL -> NOT NULL rejects the write: fail-closed) and NOT NULL.
ALTER TABLE "admin_users" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "agent_behavior" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "conversation_events" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "conversations" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "messages" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "knowledge_entries" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "order_items" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "ad_product_links" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "color_synonyms" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "colors" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "product_categories" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "product_image_colors" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "product_image_descriptions" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "product_image_embeddings" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "tenant_id" SET DEFAULT current_setting('app.tenant_id', true)::uuid, ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "admin_users" ADD CONSTRAINT "admin_users_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_behavior" ADD CONSTRAINT "agent_behavior_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversation_events" ADD CONSTRAINT "conversation_events_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_channel_id_channels_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "knowledge_entries" ADD CONSTRAINT "knowledge_entries_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ad_product_links" ADD CONSTRAINT "ad_product_links_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "color_synonyms" ADD CONSTRAINT "color_synonyms_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "colors" ADD CONSTRAINT "colors_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_categories" ADD CONSTRAINT "product_categories_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_image_colors" ADD CONSTRAINT "product_image_colors_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_image_descriptions" ADD CONSTRAINT "product_image_descriptions_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_image_embeddings" ADD CONSTRAINT "product_image_embeddings_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "agent_behavior_tenant_active_idx" ON "agent_behavior" USING btree ("tenant_id") WHERE "agent_behavior"."is_active";--> statement-breakpoint
CREATE INDEX "conversations_tenant_psid_idx" ON "conversations" USING btree ("tenant_id","psid");--> statement-breakpoint
CREATE INDEX "messages_tenant_created_idx" ON "messages" USING btree ("tenant_id","created_at");--> statement-breakpoint
CREATE INDEX "knowledge_entries_tenant_published_idx" ON "knowledge_entries" USING btree ("tenant_id","is_published");--> statement-breakpoint
CREATE INDEX "orders_tenant_status_idx" ON "orders" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "orders_conversation_draft_uq" ON "orders" USING btree ("conversation_id") WHERE "orders"."status" = 'draft';--> statement-breakpoint
CREATE INDEX "ad_product_links_tenant_ad_ref_active_idx" ON "ad_product_links" USING btree ("tenant_id","ad_ref") WHERE "ad_product_links"."is_active";--> statement-breakpoint
CREATE UNIQUE INDEX "color_synonyms_tenant_term_idx" ON "color_synonyms" USING btree ("tenant_id","term");--> statement-breakpoint
CREATE UNIQUE INDEX "colors_tenant_family_idx" ON "colors" USING btree ("tenant_id","family");--> statement-breakpoint
CREATE UNIQUE INDEX "product_categories_tenant_slug_idx" ON "product_categories" USING btree ("tenant_id","slug");--> statement-breakpoint
CREATE INDEX "products_tenant_published_idx" ON "products" USING btree ("tenant_id","is_published");--> statement-breakpoint
CREATE UNIQUE INDEX "products_tenant_sku_idx" ON "products" USING btree ("tenant_id","sku");--> statement-breakpoint
-- RLS: ENABLE (not FORCE) — the owner role keeps running migrations/backfills
-- unimpeded; the app connects as the non-owner app_runtime role (created by
-- db-init/ensureAppRole), which these policies bind. Policies are fail-closed:
-- with no app.tenant_id bound, current_setting(..., true) is NULL and matches
-- zero rows. Platform tables (tenants, plans, platform_users, api_keys,
-- usage_*) and channels are deliberately NOT under RLS — channels is the
-- pre-tenant routing table and the rest are realm-guarded (see the plan doc).
ALTER TABLE "admin_users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "agent_behavior" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "conversation_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "conversations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "knowledge_entries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "order_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "orders" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ad_product_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "color_synonyms" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "colors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "product_categories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "product_image_colors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "product_image_descriptions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "product_image_embeddings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "products" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "admin_users" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "agent_behavior" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "conversation_events" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "conversations" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "messages" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "knowledge_entries" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "order_items" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "orders" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "ad_product_links" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "color_synonyms" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "colors" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "product_categories" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "product_image_colors" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "product_image_descriptions" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "product_image_embeddings" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "products" AS PERMISSIVE FOR ALL TO public USING (tenant_id = current_setting('app.tenant_id', true)::uuid) WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);